version: '3'
services:
  frontend:
    build: ./frontend/

  ingress:
    build: ./ingress/
    ports:
      - "443:443"
    image: ingress
    volumes:
      - /ssl/:/ssl/
    restart: on-failure
    depends_on:
      - frontend
      - backend

  backend:
    build: ./backend/
    environment:
      - MONGODB_URL=...
      - SESSION_SECRET=...
      - PORT=...