version: '3'
services:
  frontend:
    build: ./frontend/

  ingress:
    build: ./ingress/
    ports:
      - "443:443"
      - '90:90'
    image: ingress
    volumes:
      - /ssl/:/ssl/
    restart: on-failure
    depends_on:
      - frontend
      - backend

  backend:
    build: ./backend/
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: ... your username ...
        ME_CONFIG_MONGODB_ADMINPASSWORD: ... your password ...
        ME_CONFIG_MONGODB_URL: mongodb://...your username...:...your password...@database:27017/...your database name...?authSource=admin
        SESSION_SECRET: ...your secret data...
        PORT: 3001
    depends_on:
      - database

  database:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: ...your username...
      MONGO_INITDB_ROOT_PASSWORD: ...your password...
      MONGO_INITDB_DATABASE: ...database name...
volumes: 
   db: 
   