version: '3.8'
services: 
  backend:
    restart: on-failure
    build: ./backend      
    environment:
      - MONGODB_URL=mongodb+srv://Ghazaryan2409:AR122333@cluster0.jh3pp.mongodb.net/OnGrid
      - SESSION_SECRET=some secrets
      - PORT=3001
  frontend:
    restart: on-failure
    build: ./frontend
  nginx:
   image: nginx:1.17.10
   depends_on:
    - frontend
    - backend
   volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
   ports:
     - 80:80